-- MySQL Script generated by MySQL Workbench
-- Sat Sep  4 21:04:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema igti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `igti` DEFAULT CHARACTER SET utf8 ;
USE `igti` ;

-- -----------------------------------------------------
-- Table `igti`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `igti`.`pessoa` (
  `cod_pessoa` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  PRIMARY KEY (`cod_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igti`.`fabricante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`fabricante` ;

CREATE TABLE IF NOT EXISTS `igti`.`fabricante` (
  `cod_fabricante` INT NOT NULL,
  `nome_fabricante` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_fabricante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igti`.`modelo_veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`modelo_veiculo` ;

CREATE TABLE IF NOT EXISTS `igti`.`modelo_veiculo` (
  `cod_modelo` INT NOT NULL,
  `descricao_modelo` VARCHAR(45) NULL,
  `cod_fabricante` INT NOT NULL,
  PRIMARY KEY (`cod_modelo`),
  INDEX `fk_modelo_veiculo_fabricante_idx` (`cod_fabricante` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_veiculo_fabricante`
    FOREIGN KEY (`cod_fabricante`)
    REFERENCES `igti`.`fabricante` (`cod_fabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igti`.`venda_veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`venda_veiculo` ;

CREATE TABLE IF NOT EXISTS `igti`.`venda_veiculo` (
  `cod_venda` INT NOT NULL,
  `data_venda` DATE NULL,
  `valor_venda` DECIMAL NULL,
  `cod_pessoa` INT NOT NULL,
  `cod_modelo` INT NOT NULL,
  PRIMARY KEY (`cod_venda`),
  INDEX `fk_venda_veiculo_pessoa1_idx` (`cod_pessoa` ASC) VISIBLE,
  INDEX `fk_venda_veiculo_modelo_veiculo1_idx` (`cod_modelo` ASC) VISIBLE,
  CONSTRAINT `fk_venda_veiculo_pessoa1`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `igti`.`pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_veiculo_modelo_veiculo1`
    FOREIGN KEY (`cod_modelo`)
    REFERENCES `igti`.`modelo_veiculo` (`cod_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
