-- MySQL Script generated by MySQL Workbench
-- Sat Sep  4 21:18:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema igti
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema igti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `igti` DEFAULT CHARACTER SET utf8 ;
USE `igti` ;

-- -----------------------------------------------------
-- Table `igti`.`pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`pessoa` ;

CREATE TABLE IF NOT EXISTS `igti`.`pessoa` (
  `cod_pessoa` INT NOT NULL,
  `genero` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igti`.`hobbie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`hobbie` ;

CREATE TABLE IF NOT EXISTS `igti`.`hobbie` (
  `cod_hobbie` INT NOT NULL,
  `hobbie` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_hobbie`))
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `igti`.`clima`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`clima` ;

CREATE TABLE IF NOT EXISTS `igti`.`clima` (
  `cod_clima` INT NOT NULL,
  `clima` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_clima`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igti`.`bebida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`bebida` ;

CREATE TABLE IF NOT EXISTS `igti`.`bebida` (
  `cod_bebida` INT NOT NULL,
  `bebida` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_bebida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igti`.`animal_estimacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`animal_estimacao` ;

CREATE TABLE IF NOT EXISTS `igti`.`animal_estimacao` (
  `cod_animal_estimacao` INT NOT NULL,
  `animal` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_animal_estimacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igti`.`pesquisa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`pesquisa` ;

CREATE TABLE IF NOT EXISTS `igti`.`pesquisa` (
  `cod_pesquisa` INT NOT NULL AUTO_INCREMENT,
  `data_pesquisa` DATE NULL,
  `cod_pessoa` INT NOT NULL,
  `cod_animal_estimacao` INT NOT NULL,
  `cod_bebida` INT NOT NULL,
  `cod_hobbie` INT NOT NULL,
  `cod_clima` INT NOT NULL,
  PRIMARY KEY (`cod_pesquisa`),
  INDEX `fk_pesquisa_pessoa_idx` (`cod_pessoa` ASC) VISIBLE,
  INDEX `fk_pesquisa_hobbie1_idx` (`cod_hobbie` ASC) VISIBLE,
  INDEX `fk_pesquisa_clima1_idx` (`cod_clima` ASC) VISIBLE,
  INDEX `fk_pesquisa_bebida1_idx` (`cod_bebida` ASC) VISIBLE,
  INDEX `fk_pesquisa_animal_estimacao1_idx` (`cod_animal_estimacao` ASC) VISIBLE,
  CONSTRAINT `fk_pesquisa_pessoa`
    FOREIGN KEY (`cod_pessoa`)
    REFERENCES `igti`.`pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_hobbie1`
    FOREIGN KEY (`cod_hobbie`)
    REFERENCES `igti`.`hobbie` (`cod_hobbie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_clima1`
    FOREIGN KEY (`cod_clima`)
    REFERENCES `igti`.`clima` (`cod_clima`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_bebida1`
    FOREIGN KEY (`cod_bebida`)
    REFERENCES `igti`.`bebida` (`cod_bebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisa_animal_estimacao1`
    FOREIGN KEY (`cod_animal_estimacao`)
    REFERENCES `igti`.`animal_estimacao` (`cod_animal_estimacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igti`.`jogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`jogo` ;

CREATE TABLE IF NOT EXISTS `igti`.`jogo` (
  `cod_jogo` INT NOT NULL,
  `nome_jogo` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_jogo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igti`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`pais` ;

CREATE TABLE IF NOT EXISTS `igti`.`pais` (
  `cod_pais` INT NOT NULL,
  `nome_pais` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igti`.`jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `igti`.`jogador` ;

CREATE TABLE IF NOT EXISTS `igti`.`jogador` (
  `cod_jogador` INT NOT NULL,
  `nome_jogador` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `num_vitorias` INT NULL,
  `num_derrotas` INT NULL,
  `total_partidas` INT NULL,
  `cod_pais` INT NOT NULL,
  `cod_jogo` INT NOT NULL,
  PRIMARY KEY (`cod_jogador`),
  INDEX `fk_jogador_pais1_idx` (`cod_pais` ASC) VISIBLE,
  INDEX `fk_jogador_jogo1_idx` (`cod_jogo` ASC) VISIBLE,
  CONSTRAINT `fk_jogador_pais1`
    FOREIGN KEY (`cod_pais`)
    REFERENCES `igti`.`pais` (`cod_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jogador_jogo1`
    FOREIGN KEY (`cod_jogo`)
    REFERENCES `igti`.`jogo` (`cod_jogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
